-- MySQL Script generated by MySQL Workbench
-- Fri Oct 30 05:17:30 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema garden
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema garden
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `garden` DEFAULT CHARACTER SET utf8 ;
USE `garden` ;

-- -----------------------------------------------------
-- Table `garden`.`dostawcy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garden`.`dostawcy` (
  `IDDostawcy` INT(11) NOT NULL,
  `NazwaDostawcy` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `NazwaKontaktu` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `StanowiskoKontaktu` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `Adres` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `Miasto` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `Stan` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `KodPocztowy` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `NrTelefonu` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `NrFaksu` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`IDDostawcy`),
  UNIQUE INDEX `IDDostawcy_UNIQUE` (`IDDostawcy` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `garden`.`kategorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garden`.`kategorie` (
  `IDKategorii` INT(11) NOT NULL,
  `NazwaKategorii` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `Opis` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`IDKategorii`),
  UNIQUE INDEX `IDKategorii_UNIQUE` (`IDKategorii` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `garden`.`klienci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garden`.`klienci` (
  `IDKlienta` INT(11) NOT NULL,
  `Imie` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Nazwisko` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `Adres` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `Miasto` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `Region` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `KodPocztowy` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `Kraj` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `NrTelefonu` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`IDKlienta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `garden`.`pracownicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garden`.`pracownicy` (
  `IDPracownika` INT(11) NOT NULL,
  `Imie` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `Nazwisko` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `Stanowisko` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `Adres` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `Miasto` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `Stan` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `KodPocztowy` INT(11) NULL DEFAULT NULL,
  `TelDomowy` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `DataUrodzenia` DATE NULL DEFAULT NULL,
  `DataZatrudnienia` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`IDPracownika`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `garden`.`produkty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garden`.`produkty` (
  `IDProduktu` INT(11) NOT NULL,
  `NazwaProduktu` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `NazwaLacinska` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `IDDostawcy` INT(11) NULL DEFAULT NULL,
  `IDKategorii` INT(11) NULL DEFAULT NULL,
  `IloscNaJednostke` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `CenaJednostkowa` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `JednostekNaStanie` INT(11) NULL DEFAULT NULL,
  `JednostekNaZamowieniu` INT(11) NULL DEFAULT NULL,
  `PoziomDomowienia` INT(11) NULL DEFAULT NULL,
  `Wycofany` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`IDProduktu`),
  INDEX `fk_dost_idx` (`IDDostawcy` ASC) VISIBLE,
  INDEX `fk_kat_idx` (`IDKategorii` ASC) VISIBLE,
  CONSTRAINT `fk_dost`
    FOREIGN KEY (`IDDostawcy`)
    REFERENCES `garden`.`dostawcy` (`IDDostawcy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kat`
    FOREIGN KEY (`IDKategorii`)
    REFERENCES `garden`.`kategorie` (`IDKategorii`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `garden`.`przewoznik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garden`.`przewoznik` (
  `IDPrzewoznika` INT(11) NOT NULL,
  `Firma` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `Kontakt` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `Ulica` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `Miasto` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `Stan` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `KodPocztowy` INT(11) NULL DEFAULT NULL,
  `Telefon` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`IDPrzewoznika`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `garden`.`zamowienia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garden`.`zamowienia` (
  `IDZamowienia` INT(11) NOT NULL,
  `IDKlienta` INT(11) NULL DEFAULT NULL,
  `PrzedstKonta` INT(11) NULL DEFAULT NULL,
  `DataZamowienia` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `DataWysylki` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `WyslanePrzez` INT NULL DEFAULT NULL,
  `KosztWysylki` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `NazwaWysylki` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `AdresWysylki` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `MiastoWysylki` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `RegionWysylki` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `KodPocztowyWysylki` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `KrajWysylki` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `DataWymagana` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`IDZamowienia`),
  INDEX `fk_klient_idx` (`IDKlienta` ASC) VISIBLE,
  INDEX `fk_prac_idx` (`PrzedstKonta` ASC) VISIBLE,
  INDEX `fk_przew_idx` (`WyslanePrzez` ASC) VISIBLE,
  CONSTRAINT `fk_klient`
    FOREIGN KEY (`IDKlienta`)
    REFERENCES `garden`.`klienci` (`IDKlienta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prac`
    FOREIGN KEY (`PrzedstKonta`)
    REFERENCES `garden`.`pracownicy` (`IDPracownika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_przew`
    FOREIGN KEY (`WyslanePrzez`)
    REFERENCES `garden`.`przewoznik` (`IDPrzewoznika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `garden`.`szczegoly_zamowienia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garden`.`szczegoly_zamowienia` (
  `IDZamowienia` INT(11) NOT NULL,
  `IDProduktu` INT(11) NOT NULL,
  `CenaJednostkowa` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL DEFAULT NULL,
  `Ilosc` INT(11) NULL DEFAULT NULL,
  `Rabat` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`IDZamowienia`, `IDProduktu`),
  INDEX `fk_prod_idx` (`IDProduktu` ASC) VISIBLE,
  CONSTRAINT `fk_prod`
    FOREIGN KEY (`IDProduktu`)
    REFERENCES `garden`.`produkty` (`IDProduktu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zam`
    FOREIGN KEY (`IDZamowienia`)
    REFERENCES `garden`.`zamowienia` (`IDZamowienia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
